### ISSUE TITLE
"Seeking Assistance with an Issue Related to Gateway Disconnection in Hummingbot"

### ISSUE THREAD

**Issue by Baiqu** [hummingbot/deploy-examples#29]
![屏幕截图 2023-07-22 124149](https://github.com/hummingbot/deploy-examples/assets/5540970/3470c7d7-4576-45a4-b2ab-99c3f3b6d639)
I am experiencing an issue while using the gateway that I set up with Docker. Specifically, the problem arises when I use 'gateway connect quickswap' in Hummingbot, and after entering 'polygon, mainnet', the connection is lost. Upon investigation, I noticed that the gateway container displayed a 404 error, indicating that the resource could not be found. I'd appreciate any assistance you can provide.

**Comment by rapcmia** [comment]
Hi @Baiqu, good day
I am not able to replicate the 404 error perhaps something to do with your connection, i am able to setup quickswap and run for few minutes got no 404 local network

![image](https://github.com/hummingbot/deploy-examples/assets/73840223/37285a3e-968e-48ba-a567-7256834142df)
